version: 2
jobs:
  test:
    working_directory: ~/likecoin-button
    docker:
      - image: node:10
    steps:
      - checkout
      - restore_cache:
          key: likecoin-button-{{ .Environment.CACHE_UUID }}-{{ checksum "src/package.json" }}-{{ checksum "src/package-lock.json" }}
      - restore_cache:
          key: likecoin-button-{{ .Environment.CACHE_UUID }}-{{ checksum "functions/package.json" }}-{{ checksum "functions/package-lock.json" }}
      - run:
          name: Dependencies
          command: npm --prefix src install && npm --prefix functions install && cp src/nuxt.config.js functions/
      - run:
          name: Lint Test
          command: npm --prefix src run lint && npm --prefix functions run lint
      - run:
          name: Build
          command: npm --prefix src run build
      - run:
          name: Server Test
          command: npm --prefix src start
          background: true
      - run:
          name: Curl Test
          command: |
            sleep 5
            curl --retry 10 --retry-delay 5 -v http://127.0.0.1:3000/
      - save_cache:
          key: likecoin-button-{{ .Environment.CACHE_UUID }}-{{ checksum "src/package.json" }}-{{ checksum "src/package-lock.json" }}
          paths:
            - ./src/node_modules
      - save_cache:
          key: likecoin-button-{{ .Environment.CACHE_UUID }}-{{ checksum "functions/package.json" }}-{{ checksum "functions/package-lock.json" }}
          paths:
            - ./functions/node_modules
  deploy_rinkeby:
    working_directory: ~/likecoin-button
    docker:
      - image: node:10
    steps:
      - checkout
      - run:
          name: Setup gcloud
          command: npm install -g firebase-tools@9
      - restore_cache:
          key: likecoin-button-{{ .Environment.CACHE_UUID }}-{{ checksum "src/package.json" }}-{{ checksum "src/package-lock.json" }}
      - restore_cache:
          key: likecoin-button-{{ .Environment.CACHE_UUID }}-{{ checksum "functions/package.json" }}-{{ checksum "functions/package-lock.json" }}
      - run:
          name: Dependencies
          command: npm --prefix src install && npm --prefix functions install && cp src/nuxt.config.js functions/
      - deploy:
          name: Deploy
          command: |
            firebase use dev
            SENTRY_PUBLISH_RELEASE=TRUE \
            SENTRY_DSN=${TEST_SENTRY_DSN} \
            SENTRY_PROJECT=${TEST_SENTRY_PROJECT} \
            FACEBOOK_PIXEL_ID=${TEST_FACEBOOK_PIXEL_ID} \
            firebase deploy
          environment:
            IS_TESTNET: true
  deploy_mainnet:
    working_directory: ~/likecoin-button
    docker:
      - image: node:10
    steps:
      - checkout
      - run:
          name: Setup gcloud
          command: npm install -g firebase-tools@9
      - restore_cache:
          key: likecoin-button-{{ .Environment.CACHE_UUID }}-{{ checksum "src/package.json" }}-{{ checksum "src/package-lock.json" }}
      - restore_cache:
          key: likecoin-button-{{ .Environment.CACHE_UUID }}-{{ checksum "functions/package.json" }}-{{ checksum "functions/package-lock.json" }}
      - run:
          name: Dependencies
          command: npm --prefix src install && npm --prefix functions install && cp src/nuxt.config.js functions/
      - deploy:
          name: Deploy
          command: |
            firebase use default
            SENTRY_PUBLISH_RELEASE=TRUE \
            firebase deploy
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - hold_deploy_rinkeby:
          type: approval
          filters:
            branches:
              only:
                - master
                - develop
                - /feature.*/
          requires:
           - test
      - hold_deploy_mainnet:
          type: approval
          filters:
            branches:
              only: master
          requires:
           - test
      - deploy_rinkeby:
          requires:
            - hold_deploy_rinkeby
      - deploy_mainnet:
          requires:
            - hold_deploy_mainnet
